require("lib.factory.lib")

require "script.layout"
require "script.factory-buildings"
require "script.connections.connections"
require "script.roboport"
require "script.blueprint"
require "script.camera"
require "script.travel"
require "script.overlay"
require "script.pollution"
require "script.electricity"
require "script.greenhouse"
require "script.lights"
require "script.borehole-pump"
require "script.migration"
require "script.factory-layouts"
require "script.factory-lifecycle"
require "script.factory-manager"
require "script.factory-map"